### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by kevinniu666** [DEVmachine-fr/cert-manager-alidns-webhook#1]
Hi oliver,
I have cloned your previous cert-manager with alidns support. looks like you have delete that repo. could you please help to advise how can i use the new one and integrate it with kubernetes?It will be highly appreciated if you can write some  documentation.Thanks.

BTW, will the SSL certificate be updated automatically?

**Comment by olivierboudet** [comment]
Hello,
Sorry for the (very) long delay. 
Yes the SSL certificate will be updated automically one month before expiration.

This is a webhook component for [cert-manager](https://cert-manager.io/docs/). You have to install cert-manager in your cluster (https://cert-manager.io/docs/installation/) and then install the alidns-webook. The installation procedure is described in the readme in this repo.

Then, you have to configure cert-manager by creating an issuer which use the alidns-solver and a certificate. See https://cert-manager.io/docs/configuration/acme/
