### ISSUE TITLE
Perhaps notification helm install with set value "groupName" would be better

### ISSUE THREAD

**Issue by incubator4** [DEVmachine-fr/cert-manager-alidns-webhook#11]
I just deploy webhook with helm and I set tu my own domain
but cluster issuer False  by certificate , certificate to certificaterequest

and finally I got challenges pending with User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "alidns-solver" in API group "this_is_my_domain" 

and i finally knew that the groupname in helm chart values should matched with (cluster)issuers.

indeed, in project this two values are not matched

**Comment by olivierboudet** [comment]
Yes, groupName in chart values and issuer must match. I will mention that in readme.

**Comment by vildenH** [comment]
不好意思，对于K8S了解的不是很深，目前也卡在这个报错。

想请问一下具体配置groupname应该填什么东西呀
