### ISSUE TITLE
Alicloud configuration started, unable to obtain certificate

### ISSUE THREAD

**Issue by mpv945** [DEVmachine-fr/cert-manager-alidns-webhook#14]
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}
Decoded configuration: {{{alidns-secrets} access-token} {{alidns-secrets} secret-key} cn-beijing}

secret ：--from-literal="access-token= （AccessKey Secret ？）--from-literal="secret-key= （AccessKey ID ？）  “ ，Do you need to configure the same namespace as "alias webhook"?

        webhook:
            config:
              accessTokenSecretRef:
                key: access-token
                name: alidns-secrets
              regionId: cn-beijing
              secretKeySecretRef:
                key: secret-key

**Comment by olivierboudet** [comment]
Since version 0.6.1, it should not be necessary to create secret in same namespace as webhook.

**Comment by MikelPan** [comment]
请问这个access-token直接使用accesskey secret可以吗
